# Maintainer tangfeixiong <fxtang@qingyuanos.com>
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: etcd
    heritage: qingyuanos.com
    name: etcd-v3-single
  name: etcd-v3-single
  # namespace: qingyuancloud
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: etcd-v3-single
      version: v3
  template:
    metadata:
      labels:
        name: etcd-v3-single
        version: v3
      name: etcd-v3-single
    spec:
      containers:
      - args:
        - --data-dir
        - /var/etcd
        - --listen-client-urls
        - 'http://0.0.0.0:2379'
        - --advertise-client-urls
        - 'http://$(ETCD_V3_SINGLE_SERVICE_HOST):$(ETCD_V3_SINGLE_SERVICE_PORT)'
        command:
        - /usr/local/bin/etcd
        image: quay.io/coreos/etcd:v3.0.7
        imagePullPolicy: IfNotPresent
        name: etcd-v3-single
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        # - containerPort: 2380
        #   name: peer
        #   protocol: TCP
        volumeMounts:
        - mountPath: /var/etcd
          name: etcd-store # etcd-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: etcd-data
      - hostPath:
          path: /tmp/k8s-vols/etcd-v3-single
        name: etcd-store
