# A headless service to create DNS records
# Maintainer tangfeixiong <fxtang@qingyuanos.com>
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    qingyuanos.io/catalog: '{"version": "v1alpha", "lib": "https://github.com/qingyuancloud/kube-harpoon"}'
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: etcd3
    qingyuanos.io/harpoon: etcd3-cluster
    qingyuanos.io/heritage: qingyuancloud
  name: etcd3-cluster
  # namespace: harpoon
spec:
  # *.etcd3-cluster.default|qingyuancloud.svc.cluster.local
  clusterIP: None
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  selector:
    qingyuanos.io/harpoon: etcd3-cluster
    qingyuanos.io/heritage: qingyuancloud
